### ISSUE TITLE
Error after iron router update

### ISSUE THREAD

**Issue by Anonyfox** [rjobanp/meteor-slide-panel#1]
After the latest update of iron-router, the following error occurs: 

```
Exception in template helper: TypeError: Cannot read property 'get' of null
    at SlidePanel.overlay (http://localhost:3000/packages/rosh93_slide-panel.js?ffa6ed7697af760913d9bdef57db402951462393:86:25)
    at Object.Template.slidePanel.helpers.overlay (http://localhost:3000/packages/rosh93_slide-panel.js?ffa6ed7697af760913d9bdef57db402951462393:238:23)
    at http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2693:16
    at http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1602:16
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?3c496d2950151d744a8574297b46d2763a123bdf:169:18)
    at Template.slidePanel.Blaze.If.HTML.DIV.class (http://localhost:3000/packages/rosh93_slide-panel.js?ffa6ed7697af760913d9bdef57db402951462393:196:22)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2454:44)
    at http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1795:16
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2029:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1794:18)
```

**Comment by rjobanp** [comment]
Hi @Anonyfox , I'm having trouble replicating this bug.
Can you confirm this is directly related to to Iron Router 1.0.4 (does the bug disappear on 1.0.3)?
Are you using the overlay option the slide panel?
Also, if you access `slidePanel._overlay` in your web console when the error occurs do you get a ReactiveVar instance?

**Comment by Anonyfox** [comment]
`slidePanel._overlay` returns `null`. 

Weird. I'll try to find the issue if possible... these are the steps I did to break it: 
- having a deployed app running (no bug)
- on my local copy, doing `meteor update` and `meteor add hammer:hammer` to play around a little.
- The error occurs. 
- The only updates from `meteor update` are from iron-\* and collection2. 

So I have a running app with no bug, and a local copy with this bug, and only these steps in between. I'll try to revert any changes step by step.

**Comment by rjobanp** [comment]
Okay thanks for the info. If `slidePanel._overlay` returns `null` then I think the `{{slidePanel}}` template is getting destroyed somewhere, and possibly re-rendered again. This could be related to where it is in relation to your router `yield` areas, or possibly something `hammer` is doing.

I would check where `{{> slidePanel}}` is included in your app. The package currently only expects the main `Template.slidePanel` to be created/rendered once, and never destroyed for the lifecycle of your app.

**Comment by Anonyfox** [comment]
I completely reverted all my changes, removed hammer.js and double-checked that `{{> slidePanel}}` is in a layout template on a position that never gets re-rendered. The bug is still there. Hmm.

**Comment by rjobanp** [comment]
Can you try the latest version of `rosh93:slide-panel` version 0.1.6? I removed the `remove` method as it's not really needed, and it should avoid the problem of setting slidePanel._overlay to null by mistake.

**Comment by Anonyfox** [comment]
removing slide-panel and adding again with the latest version: it works now. 

As a side note: I just placed {{> slidePanel}}` in a place where it gets re-rendered multiple times, and this doesn't cause any problem. Just FYI. 

I still don't know what the problem was, but thanks for your fast help! keep on the good work! :)

**Comment by rjobanp** [comment]
Great! I added the latest update to allow it to be re-rendered multiple times, so I'm assuming the problem could have been related to that. Glad to hear it's fixed.
